server:
  port: 8187
  servlet:
    context-path: /app
spring:
  main:
    banner-mode: off
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?options=--search_path%3Dtelegram_message
    username: postgres
    password: 5397
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: validate

  jackson:
    default-property-inclusion: non_absent


app:
  http:
    bot: bot
telegram-bot:
  token: "8503763341:AAHOsgfAMzDomSslCt9om_3iQG9LuxTRI8o"
  admin-id: "@daru_kanal" # Имя канала или id чата
