server:
  port: 8189
  servlet:
    context-path: /app
spring:
  main:
    banner-mode: off
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/work_time_monitor?options=--search_path%3Dupdate
    username: postgres
    password: 5397


  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update

  jackson:
    default-property-inclusion: non_absent
  servlet:
    multipart:
      enabled: true
  # Threshold after which the files are written to a disk.
      file-size-threshold: 2KB
  # Max file size.
      max-file-size: 1000MB
  # Max Request Size
      max-request-size: 5500MB

update:
  save-into: "c:/daru/build"
  run-service-command: "start \"%s:%s\" java -jar %s%s-0.0.1-SNAPSHOT.jar"
  unpack-command: "C://daru/build/7z.exe x %s"