server:
  port: 8188
  servlet:
    context-path: /app
spring:
  main:
    banner-mode: off
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?options=--search_path%3Dinformation
    username: postgres
    password: 5397


  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: validate

  jackson:
    default-property-inclusion: non_absent
  servlet:
    multipart:
      enabled: true
  # Threshold after which the files are written to a disk.
      file-size-threshold: 2KB
  # Max file size.
      max-file-size: 5500KB
  # Max Request Size
      max-request-size: 5500KB